//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalSignature
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Size { get; set; }
        public string Path { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public Nullable<byte> Status { get; set; }
        public string ServerPath { get; set; }
    }
}
