//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Huyen
    {
        public int HuyenID { get; set; }
        public string TenHuyen { get; set; }
        public string Cap { get; set; }
        public Nullable<int> TinhID { get; set; }
    }
}
