//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_HoSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_HoSo()
        {
            this.S_ComputerFile = new HashSet<S_ComputerFile>();
            this.S_VanBan = new HashSet<S_VanBan>();
        }
    
        public int HoSoID { get; set; }
        public int HopSoID { get; set; }
        public string MaHoSo { get; set; }
        public string SoHoSo { get; set; }
        public string TieuDeHoSo { get; set; }
        public string TenHoSo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> LoaiHoSoID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string ThoiHanBaoQuan { get; set; }
        public string CheDoSuDung { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<int> TongSoVanBan { get; set; }
        public string KyHieuThongTin { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<int> SoLuongTo { get; set; }
        public Nullable<int> SoLuongTrang { get; set; }
        public string TinhTrangVatLy { get; set; }
        public Nullable<int> FileCatalog { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> FontId { get; set; }
        public Nullable<int> OrganId { get; set; }
        public Nullable<int> TableOfContentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_ComputerFile> S_ComputerFile { get; set; }
        public virtual S_HopSo S_HopSo { get; set; }
        public virtual S_LoaiHoSo S_LoaiHoSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_VanBan> S_VanBan { get; set; }
    }
}
