//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_HopSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_HopSo()
        {
            this.S_HoSo = new HashSet<S_HoSo>();
        }
    
        public int HopSoID { get; set; }
        public int MucLucHoSoID { get; set; }
        public string MaHopSo { get; set; }
        public string TieuDeHopSo { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoLuongVanBan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual S_MucLucHoSo S_MucLucHoSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_HoSo> S_HoSo { get; set; }
    }
}
