//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_LuuTru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_LuuTru()
        {
            this.S_MucLucHoSo = new HashSet<S_MucLucHoSo>();
        }
    
        public int LuuTruID { get; set; }
        public Nullable<int> KhoID { get; set; }
        public int PhongID { get; set; }
    
        public virtual S_Kho S_Kho { get; set; }
        public virtual S_Phong S_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_MucLucHoSo> S_MucLucHoSo { get; set; }
    }
}
