//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_Phong()
        {
            this.S_LuuTru = new HashSet<S_LuuTru>();
        }
    
        public int PhongID { get; set; }
        public string PhongSo { get; set; }
        public Nullable<int> CoQuanID { get; set; }
        public string TenPhong { get; set; }
        public string LichSu { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> SoLuongTaiLieuGiay { get; set; }
        public Nullable<double> SoLuongTaiLieuDaSoHoa { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> NgonNguID { get; set; }
        public string CongCu { get; set; }
    
        public virtual S_CoQuan S_CoQuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_LuuTru> S_LuuTru { get; set; }
    }
}
