//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Role_URL
    {
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> MenuId { get; set; }
        public int RoleUrlId { get; set; }
    
        public virtual S_Menu S_Menu { get; set; }
        public virtual S_Role S_Role { get; set; }
    }
}
