//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G02Apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_User_Role
    {
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int UserRoleId { get; set; }
    
        public virtual S_Role S_Role { get; set; }
        public virtual S_Users S_Users { get; set; }
    }
}
