
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace G02Apis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class S_Users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public S_Users()
    {

        this.S_NhanVien = new HashSet<S_NhanVien>();

        this.S_Uers_Atuthority = new HashSet<S_Uers_Atuthority>();

        this.S_User_Role = new HashSet<S_User_Role>();

    }


    public int UserID { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string NguoiTao { get; set; }

    public string NguoiCapNhat { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.DateTime> NgayCapNhat { get; set; }

    public Nullable<short> status { get; set; }

    public Nullable<short> isDeleted { get; set; }

    public string PasswordSalt { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<S_NhanVien> S_NhanVien { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<S_Uers_Atuthority> S_Uers_Atuthority { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<S_User_Role> S_User_Role { get; set; }

}

}
